### ISSUE TITLE
Migrate workflow101: AttributeError: module 'subprocess' has no attribute 'PIPE'

### ISSUE THREAD

**Issue by D0wn3r** [viewflow/cookbook#130]
Hi,
I'm just trying to follow the README of workflow101's cookbook to run it
```
Traceback (most recent call last):
  File "/home/simco-dev/cookbook/workflow101/manage.py", line 14, in <module>
    from django.core.management import execute_from_command_line
  File "/home/simco-dev/cookbook/workflow101/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 17, in <module>
    from django.conf import settings
  File "/home/simco-dev/cookbook/workflow101/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 19, in <module>
    from django.utils.deprecation import RemovedInDjango60Warning
  File "/home/simco-dev/cookbook/workflow101/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 4, in <module>
    from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
  File "/home/simco-dev/cookbook/workflow101/venv/lib/python3.10/site-packages/asgiref/sync.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.10/asyncio/base_events.py", line 40, in <module>
    from . import events
  File "/usr/lib/python3.10/asyncio/events.py", line 204, in <module>
    class AbstractEventLoop:
  File "/usr/lib/python3.10/asyncio/events.py", line 499, in AbstractEventLoop
    stdin=subprocess.PIPE,
AttributeError: module 'subprocess' has no attribute 'PIPE'
```

**Comment by MarcoHernandez90** [comment]
They need to change the subprocess app name because it has conflict with the subprocess python module. And the requirements.txt is incomplete, we also need to install like 5 other packages to get the project running.
